
services:
  app:
    container_name: ruki-v-dom
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TELEGRAM_BOT_RESUME_TOKEN=${TELEGRAM_BOT_RESUME_TOKEN}
        - TELEGRAM_BOT_ORDER_TOKEN=${TELEGRAM_BOT_ORDER_TOKEN}
        - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_RESUME_TOKEN=${TELEGRAM_BOT_RESUME_TOKEN}
      - TELEGRAM_BOT_ORDER_TOKEN=${TELEGRAM_BOT_ORDER_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    # Если нужны тома для постоянного хранения
    # volumes:
    #   - ./data:/app/data
