
services:
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ruki-v-dom-dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
