# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '3000:3000'
#     restart: always
#     environment:
#       - NODE_ENV=production
#       - HOSTNAME=0.0.0.0
#     healthcheck:
#       test: ['CMD', 'curl', '-f', 'http://localhost:3000']
#       interval: 30s
#       timeout: 10s
#       retries: 3
#       start_period: 40s

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TELEGRAM_BOT_RESUME_TOKEN=${TELEGRAM_BOT_RESUME_TOKEN}
        - TELEGRAM_BOT_ORDER_TOKEN=${TELEGRAM_BOT_ORDER_TOKEN}
        - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    ports:
      - '3000:3000'
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - TELEGRAM_BOT_RESUME_TOKEN=${TELEGRAM_BOT_RESUME_TOKEN}
      - TELEGRAM_BOT_ORDER_TOKEN=${TELEGRAM_BOT_ORDER_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://0.0.0.0:3000']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
