version: '3.8'

services:
  app:
    container_name: ruki-v-dom
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TELEGRAM_BOT_RESUME_TOKEN=${TELEGRAM_BOT_RESUME_TOKEN}
        - TELEGRAM_BOT_ORDER_TOKEN=${TELEGRAM_BOT_ORDER_TOKEN}
        - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: on-failure:3
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_RESUME_TOKEN=${TELEGRAM_BOT_RESUME_TOKEN}
      - TELEGRAM_BOT_ORDER_TOKEN=${TELEGRAM_BOT_ORDER_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - NEXT_TELEMETRY_DISABLED=1
      - DEBUG=next*
    # Добавляем возможность просмотра логов
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    # Если нужны тома для постоянного хранения
    # volumes:
    #   - ./data:/app/data
