
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always
    env_file:
      - .env  # Подключение .env файла
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
  