services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruki-v-dom
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
