version: '3.3'

services:
  app:
    container_name: ruki-v-dom
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TELEGRAM_BOT_RESUME_TOKEN=${TELEGRAM_BOT_RESUME_TOKEN:-test_token}
        - TELEGRAM_BOT_ORDER_TOKEN=${TELEGRAM_BOT_ORDER_TOKEN:-test_token}
        - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-test_id}
    # Устанавливаем no - никогда не перезапускать
    restart: 'no'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_RESUME_TOKEN=${TELEGRAM_BOT_RESUME_TOKEN:-test_token}
      - TELEGRAM_BOT_ORDER_TOKEN=${TELEGRAM_BOT_ORDER_TOKEN:-test_token}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-test_id}
      - NEXT_TELEMETRY_DISABLED=1
    # Добавляем возможность просмотра логов
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    # Указываем, что контейнер должен быть всегда работоспособным
    healthcheck:
      disable: true
    # Если нужны тома для постоянного хранения
    # volumes:
    #   - ./data:/app/data
